# Generated by Django 5.0.2 on 2024-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesclass',
            name='recipe_img',
            field=models.ImageField(upload_to='recipe/img'),
        ),
    ]
